[versions]
agp = "8.11.1"
kotlin = "2.2.21"
android-minSdk = "29"
android-compileSdk = "36"
android-targetSdk = "36"
lib-version-name = "1.0.0"
lib-version-code = "1"

kotlinStdlib = "2.2.21"
runner = "1.7.0"
coreVersion = "1.7.0"
junit = "1.3.0"

# plugin
compose-plugin = "1.10.0-rc02"
compose-plugin-experimental = "1.10.0-alpha05"
ksp = "2.3.4"

# ui
activity-compose = "1.12.2"
lifecycle = "2.10.0-alpha07"

# functionality
color-picker = "1.0.0"
vanniktechMavenPublish = "0.35.0"

[libraries]

# ui
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" } # android only
lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-runtime = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }

compose-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "compose-plugin-experimental"}
compose-preview = { group = "org.jetbrains.compose.ui", name = "ui-tooling-preview", version.ref = "compose-plugin" }
compose-resources = { group = "org.jetbrains.compose.components", name = "components-resources", version.ref = "compose-plugin" }

color-picker = { group = "com.kborowy", name = "kolor-picker", version.ref = "color-picker" }

kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
core = { group = "androidx.test", name = "core", version.ref = "coreVersion" }
junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }

[bundles]


[plugins]
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
android-application = { id = "com.android.application"}
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechMavenPublish" }
android-lint = { id = "com.android.lint", version.ref = "agp" }
